#!/bin/sh

icon=":)"

essid=`iwgetid wlo1 --raw`
signal=`awk 'NR==3 {printf("%.0f%%",$3*10/7)}' /proc/net/wireless`

if [ -z "$essid" ]; then
    icon=":("

    essid="no wifi"
    signal=""
fi

echo "$icon"

case $BUTTON in
    1) echo "ciao"; dunstify --replace=1 "$essid $signal" "Right click to open nmtui";;
    3) echo "aho"; kitty;;
esac
