#preload = ~/Pictures/New/wallhaven-5gxr91.jpg
#preload = ~/Pictures/New/mountainportrait.jpeg
#preload = ~/Pictures/WindowsImages/Downloads/Art/october_2003.29.1.jpg
#preload = ~/Pictures/WindowsImages/Downloads/Art/sunset_at_scheveningen___a_fleet_of_fishing_vessels_at_anchor_2012.48.1.jpg

#wallpaper = HDMI-A-1,~/Pictures/New/mountainportrait.jpeg
#wallpaper = ,~/Pictures/New/wallhaven-5gxr91.jpg
#wallpaper = ,~/Pictures/WindowsImages/Downloads/Art/october_2003.29.1.jpg
#wallpaper = ,~/Pictures/WindowsImages/Downloads/Art/sunset_at_scheveningen___a_fleet_of_fishing_vessels_at_anchor_2012.48.1.jpg
#splash = false


wallpaper {
    monitor = DP-1
    path = ~/Pictures/New/wallhaven-exkg7w.jpg
    fit_mode = cover
}
wallpaper {
    monitor = HDMI-A-1
    path = /home/jelly/Pictures/Nature/wallhaven-9m5y31.jpg
    fit_mode = cover
}

splash = false
