#preload = ~/Pictures/New/wallhaven-5gxr91.jpg
#preload = ~/Pictures/New/mountainportrait.jpeg
#preload = ~/Pictures/WindowsImages/Downloads/Art/october_2003.29.1.jpg
#preload = ~/Pictures/WindowsImages/Downloads/Art/sunset_at_scheveningen___a_fleet_of_fishing_vessels_at_anchor_2012.48.1.jpg

#wallpaper = HDMI-A-1,~/Pictures/New/mountainportrait.jpeg
#wallpaper = ,~/Pictures/New/wallhaven-5gxr91.jpg
#wallpaper = ,~/Pictures/WindowsImages/Downloads/Art/october_2003.29.1.jpg
#wallpaper = ,~/Pictures/WindowsImages/Downloads/Art/sunset_at_scheveningen___a_fleet_of_fishing_vessels_at_anchor_2012.48.1.jpg
#splash = false


wallpaper {
    monitor =
    path = ~/Pictures/New/wallhaven-5gxr91.jpg
    fit_mode = cover
}

splash = false
