#!/bin/bash
NC='\033[0m' #no color
LBLUE='\033[1;34m'
YELLOW='\033[1;33m'

echo "${LBLUE}   ___     ___
  (o o)   (o o)
 (  ${YELLOW}V${LBLUE}  ) (  ${YELLOW}V${LBLUE}  ) 
/--${YELLOW}m${LBLUE}-${YELLOW}m${LBLUE}- /--${YELLOW}m${LBLUE}-${YELLOW}m${LBLUE}-${NC}"
