#!/usr/bin/lua
local options = {
    ["⏻ Shut down"] = "systemctl poweroff",
    [" Reboot"] = "systemctl reboot",
    ["󰍃 Log out"] = "hyprctl dispatch exit",
    ["󰜺 Cancel"] = "",
}

local options_string = ""
local length = 0
for key, _ in pairs(options) do
    options_string = options_string .. key .. "\n"
    length = length + 1
end
options_string = options_string:sub(1, -2)

local command = "echo -e '"
    .. options_string
    .. "' | wofi --dmenu --insensitive --prompt 'Power menu' --width 300 -k /dev/null --sort-order alphabetical --lines "
    ------------------ to change the location of the dropdown, use --location 1 (top left) or --location 3 (top right) (see --location in wofi --help)
    .. length+2

print(command)

local f = assert(
    io.popen(
        command, "r"
    )
)
local s = assert(f:read("*a"))
s = string.gsub(s, "^%s+", "")
s = string.gsub(s, "%s+$", "")
s = string.gsub(s, "[\n]+", " ")
f:close()

os.execute(options[s])
